---
# Usage: http://ruhoh.com

RuhohSpec: "2.0.alpha"

production_url : http://marcel.bowlitz.com
base_path: "/"

theme:
  name: "twitter"

posts:
  permalink: "/:categories/:title/"
  summary_lines: 20
  latest: 10

pages:
  summary_lines: 20

paginator:
  namespace: "/posts/"
  per_page: 10
