title : "Software [Over]Engineering"
tagline: "Lessons in Software Development"
author :
  name : "Marcel Valdez"
  email : marcel.valdez@live.com
  github : marcel-valdez
  twitter : MarcelValdez
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
